title: Repo for Education Industry
sass:
  sass_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Comment this out if still present
# theme: minima

